app:
  image: smsauto
  volumes:
    - "../../../../SMS_IMPORT/:/built_app/programs/server/sms/"
  ports:
    - "88:80"
    
  links:
    - mongo
  environment:
    - ROOT_URL=http://localhost
    - MONGO_URL=mongodb://mongo:27017/meteor
    - 'METEOR_SETTINGS={ 
        "DBSQLSERVER_HOST":"10.8.3.29",
        "DBSQLSERVER_PORT":"57055", 
        "DBSQLSERVER_USER":"reportvie",
        "DBSQLSERVER_PASSWORD":"reportvie",
        "DBSQLSERVER_DATABASE":"SUN_COTEDIVOIRE",
        "ADMINMAIL":"thibaut.zehi@groupensia.com"
        }'
  restart: always
mongo:
  image: mongo:latest 
  restart: always
